news/urls.py
from django.urls import path
from . import views

app_name = "news"

urlpatterns = [
    path('', views.post_list, name='post_list'),
    path('<int:year>/<int:month>/<int:day>/<slug:post>', views.post_detail, name='post_detail'),
]

newsblog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('news.urls', namespace='news')),

]

news/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from taggit.managers import TaggableManager
from django.urls import reverse
# Create your models here.

class PublishedManager(models.Manager):
    def get_queryset(self):
        return super(PublishedManager, self).get_queryset().filter(status = 'publish')

class Post(models.Model):
    STATUS = (
        ('draft', 'Draft'),
        ('publish', 'Publish'),
    )

    title = models.CharField(max_length=300)
    slug = models.SlugField(max_length=400, unique_for_date='publish')
    body = models.TextField()
    author = models.ForeignKey(User, related_name='posts', on_delete=models.CASCADE)
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add= True)
    status = models.CharField(max_length=10, choices=STATUS, default='draft')
    publish = models.DateTimeField(default=timezone.now)
    tags = TaggableManager()
    objects = models.Manager()
    published = PublishedManager()

    class Meta:
        ordering = ('-publish',)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        #pylint: disable=E1101
        return reverse('news:post_detail', args=[self.publish.year, self.publish.month, self.publish.day, self.slug])


class Comment(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField()
    body = models.TextField()
    post = models.ForeignKey(Post, related_name='comments', on_delete=models.CASCADE)
    active = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('-created',)
        
    def __str__(self):
        return self.name

news/forms.py
from django import forms
from .models import Comment

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('name', 'email', 'body')

news/views.py
from django.shortcuts import render, get_object_or_404
from .models import Comment, Post
from .forms import CommentForm
# Create your views here.
def post_list(request):
    query = None
    posts = None
    if 'query' in request.GET:
        query = request.GET['query']
        posts = Post.published.filter(title__icontains = query).order_by('-publish')
    else:
        posts = Post.published.order_by('-publish')
    return render(request, 'news/posts/post_list.html', {'posts': posts})

def post_detail(request, year, month, day, post):
    post = get_object_or_404(Post, status = 'publish', publish__year = year, publish__month = month, publish__day = day, slug = post)
    comments = post.comments.filter(active = True)
    new_comment = None
    if request.method == 'POST':
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            new_comment = comment_form.save(commit=False)
            new_comment.post = post
            new_comment.save()
    else:
        comment_form = CommentForm()
    return render(request, 'news/posts/post_detail.html', {'post': post, 'comments': comments, 'comment_form': comment_form, 'new_comment': new_comment})

news/templates/base.html
{% load static %} 
{% load news_tags %}
<!DOCTYPE html>
<html>
    <head>
        <title>{% block title %} My Blog {% endblock %}</title>
        <style>
            body {
                padding: 0;
                margin: 0;
            }
            header {
                display: flex;
                justify-content: space-between;
                background-color: #2F4F4F;
                margin: 0;
                padding: 4px;
                top: 0;
                align-items: center;
                color:#FFFAF0;
                
               
            }
            header a {
                text-decoration: none;
                color:#FFFAF0;
            }
            .logo {
                font-size: 2.2rem;
            }

            .right {
                margin: 1rem;
            }
            .right span {
                margin-left: 1rem;
            }

            .body {
                display: flex;
                flex-wrap: wrap;
                justify-content: space-evenly;

            }
            .main {
                width: 1000px;
            }
            .sidebar {
                width: 250px;
            }
            input {
                width: 25rem;
            }
            a {
                text-decoration: none;
            }
            img {
                width: 350px;
                object-fit: contain;
            }
            .detail_form input {
                width: 70%;
                border: none;
            }
            .detail_form {
                width: 60%;
                border: 1px solid grey;
                padding: 5px;
                border-radius: 5px;
                background-color: #DDDDDD;
            }
           
        </style>
    </head>
    <body>
        <header>
            <span class="logo"><a href="{% url 'news:post_list' %}">My&nbsp;Blog</a></span>
            <span class="search"><form method="GET"><input type="text" name="query" placeholder="search for anything here">
                <button><svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-search" fill="currentColor"
                xmlns="http://www.w3.org/2000/svg">
                <path fill-rule="evenodd"
                    d="M10.442 10.442a1 1 0 0 1 1.415 0l3.85 3.85a1 1 0 0 1-1.414 1.415l-3.85-3.85a1 1 0 0 1 0-1.415z" />
                <path fill-rule="evenodd"
                    d="M6.5 12a5.5 5.5 0 1 0 0-11 5.5 5.5 0 0 0 0 11zM13 6.5a6.5 6.5 0 1 1-13 0 6.5 6.5 0 0 1 13 0z" />
            </svg></button></form></span>
            <div class="right">
                <span><a href="">Contact</a></span>
                <span><a href="">About</a></span>
            </div>
        </header>
        <div class="body">
            <div class="sidebar">
                <h2>Latest Posts</h2>
                {% show_latest_posts %}
                
            </div>
            <div class="main">
                {% block content %}
                {% endblock %}
                
            </div>
        </div>
        
       
    </body>
</html>

news/templates/news/posts/latest_posts.html
<ul>
    {% for post in latest_posts %}
        <li><a href="{{post.get_absolute_url}}">{{post.title}}</a></li>
    {% empty %}
    No latest Post.
    {% endfor %}
</ul>

news/templates/news/posts/post_detail.html
{% extends 'base.html' %}
{% load news_tags %}
{% block title %} {{post.title}} {% endblock %}
{% block content %}
    <h1>{{post.title}}</h1>
    <small>Published {{post.publish}} by {{post.author}}</small>
    <p>{{post.body|markdown}}</p>
    <h3>Comments</h3>
    {% for comment in comments %}
        <div class="comment">
            <small>Created {{comment.created}} by {{comment.name}} </small>
            {{comment.body|linebreaks}}
        </div>
    {% empty %}
        No comments 😝 
    {% endfor %}  
    {% if new_comment %}
        Comment Submitted
    {% else %}
        <h3>Oya add your comment na 😇</h3>
        <form method="post" class="detail_form">
            {{comment_form.as_p}}
            {% csrf_token %}
            <input type="submit" value="Submit">
        </form>
    {% endif %}
{% endblock %}

news/templates/news/posts/post_list.html
{% extends 'base.html' %}
{% load news_tags %}
{% block content %}
    {% for post in posts %}
        <a href="{{post.get_absolute_url}}">
            <h2>{{post.title}}</h2><small>Published {{post.publish}} by {{post.author}}</small>
            <small>Published {{post.publish}} by {{post.author}}</small>
            <p>{{post.body|markdown|truncatewords_html:30}}</p>
        </a>
    {% empty %}
    No post 😝 
    {% endfor %}


{% endblock %}
        